-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "position" SET DEFAULT 0.0,
ALTER COLUMN "position" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "position" SET DEFAULT 0.0,
ALTER COLUMN "position" SET DATA TYPE DOUBLE PRECISION;
